// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmPSFIo0OEBFAMhl4SK_wfrKs3Dt0GRgg',
    appId: '1:280254215480:web:45aba9dab86a5639f5bdcd',
    messagingSenderId: '280254215480',
    projectId: 'weatherly-f947b',
    authDomain: 'weatherly-f947b.firebaseapp.com',
    storageBucket: 'weatherly-f947b.firebasestorage.app',
    measurementId: 'G-NK1E8DLWKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMXdW30HkCQ-fBZbxzSpg0PRGhzlPwscQ',
    appId: '1:280254215480:android:f4c1dc6003f25a65f5bdcd',
    messagingSenderId: '280254215480',
    projectId: 'weatherly-f947b',
    storageBucket: 'weatherly-f947b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaQRKdyMVXSR4hOn4DCQKBD_MyBwLXQts',
    appId: '1:280254215480:ios:4ac3aa51b6d80fc0f5bdcd',
    messagingSenderId: '280254215480',
    projectId: 'weatherly-f947b',
    storageBucket: 'weatherly-f947b.firebasestorage.app',
    iosBundleId: 'com.example.weatherly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaQRKdyMVXSR4hOn4DCQKBD_MyBwLXQts',
    appId: '1:280254215480:ios:4ac3aa51b6d80fc0f5bdcd',
    messagingSenderId: '280254215480',
    projectId: 'weatherly-f947b',
    storageBucket: 'weatherly-f947b.firebasestorage.app',
    iosBundleId: 'com.example.weatherly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmPSFIo0OEBFAMhl4SK_wfrKs3Dt0GRgg',
    appId: '1:280254215480:web:72dfe2df3e43a95ef5bdcd',
    messagingSenderId: '280254215480',
    projectId: 'weatherly-f947b',
    authDomain: 'weatherly-f947b.firebaseapp.com',
    storageBucket: 'weatherly-f947b.firebasestorage.app',
    measurementId: 'G-FBD9TKVX2J',
  );
}
